name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main  # or your desired branch

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v3  # Corrected version
      with:
        server: ftp.samkirkland.com            # Replace with your actual FTP server
        username: myFtpUserName                # Replace with your FTP username
        password: ${{ secrets.ftp_password }}  # Use the GitHub secret for your FTP password
